### PR TITLE
Windows support based on sockets

### PR DESCRIPTION
**Pull request by ncreep**

### CODE REVIEW

**Comment by mgsloan** [comment]
Hey!  Sorry that this is languishing, gotta figure out why travis isn't happy with it.  I'll hopefully get around to poking at that tomorrow.

**Comment by ncreep** [comment]
Travis seems to be unhappy randomly (maybe he has mood swings), I've seen similar behavior on `master` even without my changes. Rerunning will most likely yield a successful build.

The failure to start running `TestSuite` as a whole happens around half the times (`master` included).
Random failures inside `TestSuite` are more rare, but happen on `master` as well, like, e.g., [this](https://travis-ci.org/ncreep/ide-backend/jobs/81380874) build.

I'm inclined to think that it's some concurrency problem with `TestSuite` itself, but I've really no idea what it is. 
Also, can upgrading to a newer version of `stack` affect anything?

**Comment by mgsloan** [comment]
Yeah, it'd probably be good to update our stack version, but I doubt it's affecting anything.  I've requested another build

**Comment by ncreep** [comment]
Rebased on latest changes

**Comment by mgsloan** [comment]
Thanks a bunch for all your hard work!

**Comment by ncreep** [comment]
Great, glad to see this merged.

**Pull request merged**
