### PR TITLE
Fix build failures for GHC 7.4 in ide-backend-common

### PR DESCRIPTION
**Pull request by hvr**

### CODE REVIEW

**Comment by hvr** [comment]
GHC 7.2 would be fixable too with some effort, but I don't think it's worth the trouble w/ GHC 7.2 being a tech-preview release. GHC 7.0 is out of reach, as the code relies heavily on `DeriveGenerics`

**Comment by hvr** [comment]
PS: source-repo and bug-report urls are missing from the `.cabal` files; I had to lucky guess where the issue tracker was... :-)

**Comment by snoyberg** [comment]
Thank you for the PR, but I'm not sure if this is worth merging in. GHC 7.4 is probably not properly supported anyway due to changes in the semantics of the ghc library. Assigning to @mgsloan for review.

**Comment by hvr** [comment]
@snoyberg if you don't plan to support GHC 7.4, then please set `base >= 4.6` (and the other lower bounds) in future releases to signal this more explicitly

**Comment by snoyberg** [comment]
I would have, but I just copied the bounds from work someone else did.

**Comment by mgsloan** [comment]
Sorry for letting this languish.  ide-backend-server does support 7.4.2, so it makes sense to be able to build with 7.4.2.

I've merged this, but I haven't tested that it builds with 7.4.2, as I'm assuming the build worked for @hvr.

**Pull request merged**
