### PR TITLE
Hide the existence of ide-backend-rts

### PR DESCRIPTION
**Pull request by jcpetruzza**
This is an implementation of the idea discussed in #289: to embed in ide-backend-server's binary a properly compiled and packaged version of its rts library, so that clients need not worry anymore about having that special dependency installed somewhere the server can find it.

The important changes are in ide-backend-server's `Setup.hs` script, that now must also build and pack the rts in advance (moved to ide-backend-server's source dir), ensuring:

1. that exactly the same version of ghc is used, and
2. that it is packed as a relocatable package (so that it doesn't matter where the server puts it at runtime).

We ensure 1) as follows: whenever `Setup.hs configure` is run, we also run `Setup.hs configure` inside the rts directory, passing the same command line parameters we received (overriding the installation
directory). For 2), we cannot rely on Cabal (not yet, at least,  support is coming in Cabal-1.24, it looks), so we first use Cabal to package the rts using absolute paths and then manually insert the required `${pkgroot}` in the "installed package configuration".

### CODE REVIEW

**Comment by jcpetruzza** [comment]
Custom setups, the _other_ cabal hell...

It turns out that cabal's interface to the configured hc-pkg changed in version 1.22 (the one in ghc 7.10), so the setup script fails when run with ghc 7.8, as the failed CI build shows... I'll see what can be done to have something that works with ghc 7.6 and 7.8 as well, then

**Comment by jcpetruzza** [comment]
This version of the setup script only uses functions that have been in the Cabal API for long

**Comment by mgsloan** [comment]
This looks excellent, thanks!!!  I'll review + test soon, probably tomorrow.

**Comment by lukexi** [comment]
I've given Daniel's branch a whirl locally (as it greatly increases the usability of https://github.com/lukexi/stack-ide-sublime : ) ) and it's working great for me. Thanks a ton Daniel!

**Comment by mgsloan** [comment]
Looks good to me, awesome work!

**Comment by urbanslug** [comment]
Okay I'm in awe. I didn't know that one could have a binary tar-gzip'ed inside another binary what is going on here?

**Pull request merged**
